### ISSUE TITLE
Cannot build with NUC_EOS=0

### ISSUE THREAD

**Issue by eschnett** [evanoconnor/GR1D#18]
I want to build without support for a nuclear equation of state. I'm setting `NUC_EOS=0` in the `make.inc`. This leads to the error
```
Undefined symbols for architecture x86_64:
  "_nuc_eos_full_", referenced from:
      _m1_updateeas_._omp_fn.0 in M1_updateeas.o
ld: symbol(s) not found for architecture x86_64
```
How can I resolve this?

**Comment by evanoconnor** [comment]
I just pushed a commit for this.  Two missing compiler flags.

**Comment by eschnett** [comment]
Thanks!
